### PR TITLE
Fix MissingMethodException in I18nFieldsHelper and new PersistenceEventListener

### PR DESCRIPTION
**Pull request by aberbenni**

### CODE REVIEW

**Comment by jorgeuriarte** [comment]
Thanks, Alessandro. We'll try to integrate your pull request as soon as possible (currently working on that branch, as you already noticed ;) )

**Comment by aberbenni** [comment]
Thanks for your quick reply. I'm happy to find a plugin in active development, it's rare these days. I hope the pull request will be useful.

**Comment by fniwes** [comment]
Thanks for the pull request, it is very useful.

However I have a question. Why did you use containsKey instead of contains? In the configuration the key i18nFields.redisLocais is supposed to be a List, not a Map. And if a I use containsKey the demobinding project fails with 

"No signature of method: java.util.ArrayList.containsKey() is applicable for argument types: (java.lang.String) values"

How are you using that key?

**Comment by aberbenni** [comment]
The reason is that without that change I receive this error:

```
Error 2013-07-11 08:57:39,036 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [GET] /test/alert/create
No signature of method: groovy.util.ConfigObject.contain() is applicable for argument types: (java.lang.String) values: [en_US]
Possible solutions: toString(), toString(), notify(), containsKey(java.lang.Object), countBy(groovy.lang.Closure), count(groovy.lang.Closure). Stacktrace follows:

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:render>: Error evaluating expression [alertInstance?.title_en_US] on line [10]: groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.contain() is applicable for argument types: (java.lang.String) values: [en_US]
Possible solutions: toString(), toString(), notify(), containsKey(java.lang.Object), countBy(groovy.lang.Closure), count(groovy.lang.Closure)
```

**Comment by aberbenni** [comment]
I synched with the latest version, but the exception (mentioned above) is still there.
I'll open a new issue.

**Comment by fniwes** [comment]
Could you please, send to us, your Config.groovy? If you run the project
called demobinding that is the _test_ folder, do you have the same issue?

The format of configuration should be:

i18nFields {
    // Which locales do we know
    locales = ["es_ES", "en_US", "fr_FR"]

```
// Of the known locales, which locales should be stored in redis
redisLocales = ["en_US", "fr_FR"]

// If can not fetch a locale from redis, which non-redis locale should
```

we use
    defaultLocale = "es_ES"
}

Please, notice that the redisLocales configuration IS a list. (not a
string, nor a map)
Is your project configured this way? If you check all that and still have
the problem.. could you send us your project (or some smaller project with
the issue so we can debug it?

I say all this because yesterday we were working in this plugin (which is
being used in one of our projects) and with your recommendations we have
the problem that containsKey do not exists.

Thanks a lot for your help and your patience.
Also, if you like, you could try the new version that we pushed yesterday.
Have some important bugfixes, still have others important bugs that will be
fixing tomorrow, and even when it have your changes merged, we ended up
rewriting everything again because some very weird problems... but I hope
it is for the best :)

Sorry about my english, I just woke up and I have not had my coffee yet.

**Comment by aberbenni** [comment]
Here is my conf:

```
i18nFields {
    locales = ['en_US', 'it_IT']
}
```

I'm missing **redisLocales** and **defaultLocale** but this happens silently, no warning/exception.

I'll try the new format and let you know.

**Comment by fniwes** [comment]
Ahhh oka.. I think that is the problem !! We do not support that missing
keys..
Could you please modify it like:

i18nFields {
    locales = ['en_US', 'it_IT'],
    redisLocales = [],
    defaultLocale='en_US'
}

We should fix the behaviour when the keys are not present, but in the
meantime if you change your configuration as it is in my example, should
work for you.

Unfortunatle the others branches were destroyed by my fault, but If you
goes back in 0.6.x branch to before my first commit, it should be way more
stable release (but do not contains redis support)

**Pull request merged**
